In [ ]:
import numpy as np

In [23]:
# Q1. Program to create a numpy array starting from 2 till 50 with stepsize of 3

arr= np.arange(2,51,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

In [7]:
#Q2. accept two list and convert it to numpy arrays. conatenate , sort arrays and print
lst1=[]
lst2=[]
print( "Enter 5 list elements in list1 : ")
for i in range(0,5):
    ele=int(input())
    lst1.append(ele)

print( "Enter 5 list elements in list2 : ")
for i in range(0,5):
    ele=int(input())
    lst2.append(ele)
print(lst1,lst2)

#convert list to array
arr1=np.array(lst1)
arr2=np.array(lst2)

# concatenating arrays
arr=np.concatenate((arr1, arr2))
print("Concatenating arrays: ",arr)

#sorting arrays
print("Sorted arrays are :\n",np.sort(arr1), "\n", np.sort(arr2))

Enter 5 list elements in list1 : 
2
4
2
3
5
Enter 5 list elements in list2 : 
6
3
1
5
2
[2, 4, 2, 3, 5] [6, 3, 1, 5, 2]
Concatenating arrays:  [2 4 2 3 5 6 3 1 5 2]
Sorted arrays are :
 [2 2 3 4 5] 
 [1 2 3 5 6]


In [13]:
# Q3. code to find the dimension of a ndarray and its size

arr=np.array([[1,2,3],[1,2,3]])

arr.shape  #code to find the dimension of array
arr.size   #code find the size the size of array
print(arr.shape, arr.size)

(2, 3) 6


In [34]:
# Q4.Code to convert 1D array to 2D array with examples

#using .reshape() we can convert 1D array to 2D array. Eg-

arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1D array
two_D=arr.reshape(3,4)
print("1D array : \n", arr, "\n 2D array :\n", two_D )

1D array : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12] 
 2D array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
#Q5. stack two square numpy arrays vertically and horizontally

A=np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16] ])
B=np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16] ])
print("array A: \n Vertical stacking- \n",np.vstack(A), "\nHorizontal stacking- ", np.hstack(A))
print("array B: \n Vertical stacking- \n",np.vstack(B), "\nHorizontal stacking- ", np.hstack(B))


array A: 
 Vertical stacking- 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
Horizontal stacking-  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
array B: 
 Vertical stacking- 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 
Horizontal stacking-  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
